server:
  port: 8080

spring:
  application:
    name: nome-api

  datasource:
    # Quando rodando via docker run, use o IP da sua máquina ou host.docker.internal
    # Quando rodando local (sem Docker), use localhost
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:nomesdb}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update        # cria/atualiza a tabela automaticamente
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

logging:
  level:
    com.example: DEBUG
    org.springframework.web: INFO
